kubeflow/mxnet-operator

- OWNERS
Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/3)
> owner: Add gaocegege

- OWNERS
Sorry for the typo
Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/4)
> OWNERS: Fix a typo

- ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/9)
> add roadmap items (#6)

- .idea/vcs.xml
- Gopkg.toml
- cmd/mxnet-operator.v2/app/server.go
- examples/mxnet-operator.v2/crd-v1alpha2.yaml
- pkg/apis/mxnet/v1alpha2/register.go
- pkg/apis/mxnet/v1alpha2/types.go
- pkg/controller.v2/mxnet/job.go
- pkg/controller.v2/mxnet/pod.go
- pkg/controller/controller.go
- pkg/trainer/replicas.go
- pkg/trainer/training.go
- pkg/util/k8sutil/k8sutil.go
Migrate new commits from tf-operator to mxnet-operator (from Sep 3 to Oct 28, 2018)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/13)
> Synchronise mxnet-operator and tf-operator

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/18)
> Add auto-tuning help to README

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/19)
> fix a bug in README 

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/20)
> Add OWNER KingOnTheStar

- pkg/controller.v2/mxnet/status.go
fix bug: tunerTracker and tunerServer won't stop while tuner has been completed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/21)
> fix bug: tunerTracker and tunerServer won't stop while tuner has been completed

- examples/mxnet-operator.v2/tune/Dockerfile
- examples/mxnet-operator.v2/tune/mx_job_tune_gpu.yaml
- examples/mxnet-operator.v2/tune/start-job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/22)
> Change working directory in the tune mode

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/23)
> Update examples with correct path

- .gitignore
- Dockerfile
- manifests/deployment.yaml
- manifests/rbac.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/25)
> fix Dockerfile to follow latest change and rearrange directory

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/26)
> Update README to reflect latest change

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/30)
> update README to add alternative solution to deploy operator

- pkg/controller.v1beta1/mxnet/pod.go
ref  kubeflow/tf-operator#957
@suleisl2000 @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/35)
> Use kube-batch as scheduler by default when gang-scheduling is enabled

- OWNERS
/assign @suleisl2000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/42)
> add wackxu to OWNERS

- Gopkg.lock
- Gopkg.toml
- cmd/mxnet-operator.v1/app/options/options.go
- cmd/mxnet-operator.v1/app/server.go
- pkg/controller.v1/mxnet/controller.go
- pkg/controller.v1/mxnet/status.go
- pkg/controller.v1beta1/mxnet/controller.go
- pkg/controller.v1beta1/mxnet/status.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
- vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
- vendor/github.com/kubeflow/tf-operator/pkg/control/pod_control.go
- vendor/github.com/kubeflow/tf-operator/pkg/control/service_control.go
/assign @suleisl2000 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/41)
> Sync with tf-operator

- Gopkg.lock
- Gopkg.toml
- pkg/controller.v1/mxnet/status.go
- pkg/controller.v1beta1/mxnet/status.go
Related: kubeflow/tf-operator#1022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/44)
> Skip condition update when succeeded and bump tf-operator to v0.5.3 version

- pkg/controller.v1/mxnet/controller.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/45)
> fix bug for check PodPending

- pkg/controller.v1/mxnet/job.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/46)
> fix wrong api version when delete mxjob

- pkg/common/util/v1/testutil/util.go
- pkg/controller.v1/mxnet/controller.go
- pkg/controller.v1/mxnet/controller_test.go
ref https://github.com/kubeflow/pytorch-operator/pull/146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/47)
> Renaming labels to consistent format

- pkg/controller.v1/mxnet/pod.go
ref https://github.com/kubeflow/tf-operator/pull/1032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/48)
> set annotation automatically when EnableGangScheduling is set to true

- CONTRIBUTING.md
- README.md
- hack/update-codegen.sh
As we migrate to go modules and update linter configs, I add a new page to give contributor more guidance on basic setup and development flow.
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/mxnet-operator/58)
> Update Contributing docs for recent go changes

- README.md
Miscellaneous enhancements on the README.
> Enhancements on README.md

- OWNERS
> Add Jiaxin to reviewers

- examples/tune/README.md
> Fix Python script name and add links

- README.md
- manifests/kustomization.yaml
Resolve #54
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
> Add Kustomize package deployable on its own

- OWNERS
Contribution list:
https://github.com/kubeflow/mxnet-operator/pulls?q=is%3Apr+author%3AJeffwan+is%3Aclosed
> Add Jeffwan to approvers

- RELEASE.md
Signed-off-by: yuan.tang <yuan.tang@antfin.com>
> Add release document

- examples/train/byteps_dist_gpu_v1.yaml
- pkg/controller.v1/mxnet/pod.go
- pkg/controller.v1/mxnet/pod_test.go
support byteps in v1 version. see https://github.com/kubeflow/mxnet-operator/pull/82, which is for v1beta1 version.
> support byteps in v1
